import '../switch_account_bottomsheet/widgets/switch_account_item_widget.dart';import 'controller/switch_account_controller.dart';import 'models/switch_account_item_model.dart';import 'package:flutter/material.dart';import 'package:testing/core/app_export.dart';import 'package:testing/widgets/custom_icon_button.dart';
// ignore_for_file: must_be_immutable
class SwitchAccountBottomsheet extends StatelessWidget {SwitchAccountBottomsheet(this.controller);

SwitchAccountController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: size.width, padding: getPadding(left: 24, top: 8, right: 24, bottom: 8), decoration: AppDecoration.outlineGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgFrame, height: getVerticalSize(3.00), width: getHorizontalSize(38.00)), Padding(padding: getPadding(top: 23), child: Text("lbl_switch_account".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold24)), Container(height: getVerticalSize(1.00), width: getHorizontalSize(380.00), margin: getMargin(top: 24), decoration: BoxDecoration(color: ColorConstant.gray200)), Padding(padding: getPadding(top: 23), child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(24.00));}, itemCount: controller.switchAccountModelObj.value.switchAccountItemList.length, itemBuilder: (context, index) {SwitchAccountItemModel model = controller.switchAccountModelObj.value.switchAccountItemList[index]; return SwitchAccountItemWidget(model);}))), Align(alignment: Alignment.centerLeft, child: Padding(padding: getPadding(top: 24, bottom: 28), child: Row(children: [CustomIconButton(height: 60, width: 60, onTap: () {onTapBtnClose();}, child: CustomImageView(svgPath: ImageConstant.imgClose60x60)), Padding(padding: getPadding(left: 20, top: 18, bottom: 19), child: Text("lbl_add_account".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold18Gray900))])))]))); } 
onTapBtnClose() { Get.back(); } 
 }
